TestApp/Models/DataContext.cs
using System.Data.Entity;

namespace TestApp.Models
{
    public class DataContext:DbContext
    {
        public DataContext():base("PersonRelations")
        {
            Database.SetInitializer<DataContext>(new DataContextInitilaser());
        }

        public DbSet<Person> Persons { get; set; }
        public DbSet<MyPhoto> MyPhotos { get; set; }
        public DbSet<Interest> Interests { get; set; }
        public DbSet<RelationType> RelationTypes { get; set; }
        public DbSet<Relation> Relations { get; set; }
    }
}

TestApp/Models/DataContextInitilaser.cs
using System.Collections.Generic;
using System.Data.Entity;

namespace TestApp.Models
{
    public class DataContextInitilaser:DropCreateDatabaseIfModelChanges<DataContext>
    {
        protected override void Seed(DataContext context)
        {
            new List<RelationType>
            {
                new RelationType {Title = "Друг"},
                new RelationType {Title = "Враг"},
                new RelationType {Title = "Знакомый"},
                new RelationType {Title = "Влюблен"},
                new RelationType {Title = "Хто это??"}
            }.ForEach(item=>context.RelationTypes.Add(item));
            context.SaveChanges();
        }
    }
}

TestApp/Models/Person.cs
using System.Collections.Generic;

namespace TestApp.Models
{
    public class Person
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
        public bool IsMale { get; set; }
        public virtual Person Spouse { get; set; }
        public virtual ICollection<Relation> Relations { get; set; }
        public virtual MyPhoto Photo { get; set; }
        public virtual ICollection<Interest> Interests { get; set; }
    }

    public class Interest
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public virtual Person Person { get; set; }
    }

    public class MyPhoto
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Path { get; set; }
    }

    public class Relation
    {
        public int Id { get; set; }
        public virtual Person Person { get; set; }
        public virtual RelationType RelationType { get; set; }
    }

    public class RelationType
    {
        public int Id { get; set; }
        public string Title { get; set; }
    }

}

TestApp/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using TestApp.Models;
using TestApp.Repos;

namespace TestApp.Controllers
{
    public class PersonController : ApiController
    {
        private readonly IRepository _repository;

        public PersonController()
        {
            _repository = new DbPersonRepo();
        }

        public IEnumerable<Person> GetPersons()
        {
            return _repository.GetPersons;
        }

        public Person GetPerson(int id)
        {
            return _repository.GetPerson(id);
        }
        [HttpGet]
        public IHttpActionResult PiopleSex(bool id)
        {
            var result = _repository.GetSexPerson(id);
            return Ok(result);
        } 
    }
}

TestApp/Controllers/StartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestApp.Repos;

namespace TestApp.Controllers
{
    public class StartController : Controller
    {
        private readonly IRepository _repository;

        public StartController()
        {
            _repository = new DbPersonRepo();
        }
        // GET: Start
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PersonsDetails()
        {
            return View(_repository.GetPersons);
        }

        public ActionResult Sfj()
        {
            return View();
        }
    }
}

TestApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet"/>
    <link href="~/Content/font-awesome.min.css" rel="stylesheet"/>
    <script src="~/Scripts/jquery-2.2.3.min.js"></script>
    <script src="~/Scripts/knockout-3.4.0.js"></script>
    @RenderSection("links",false)

</head>
<body>
    <div class="leftSlide">
        <div class="wrapper">
            <div class="humburger">
                <i class="fa fa-bars" aria-hidden="true"></i>
            </div>
            <div class="leftContent">
                <img src="~/Content/img/me.png" alt="" />
                <h3>ПЕТР</h3>
                <h4>Почему Я?</h4>
                <p>Разработка - это моё хобби. Постоянно совершенствю свои навыки. Материал схватываю на лету.</p>
                <ul>
                    <li><a href="@Url.Action("Index","Start")">РЕЗЮМЕ</a></li>
                    <li>+7-928-373-16-13</li>
                </ul>
            </div>
        </div>
    </div>
<div>
    @RenderBody()
</div>
<footer></footer>
    <script type="text/javascript">
        $(document).ready(function () {
            var opn = false;
            $('.humburger').click(function () {
                if (opn === false) {
                    $(".leftSlide").css({
                        "left": "0",
                        "transition": "left 1s"
                    });
                    opn = true;
                } else {
                    $(".leftSlide").css({
                        "left": "-250px",
                        "transition": "left 1s"
                    });
                    opn = false;
                }
        });
    });
    </script>
    @RenderSection("scripts", false)
</body>
</html>

TestApp/Views/Shared/_sfj.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/sfj.css" rel="stylesheet" />
    <link href="~/Content/fonts.css" rel="stylesheet" />
</head>
<body>
<header>
    <div class="title">
        <h1>Поважный Петр Александрович</h1>
        <h2>WEB - DEVELOP/ASP/MVC/HTML/CSS/jQ/MVVM/.Net/</h2>
    </div>
</header>
<div class="bContent">
    <div class="contWrap">
        @RenderBody()
    </div>
</div>
<footer>
    foot
</footer>
</body>
</html>

TestApp/Views/Start/Index.cshtml
@{
    ViewBag.Title = "О Авторе";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section links{
<link href="~/Content/mainCSS.css" rel="stylesheet" />
}
<div class="container">
    <div class="row">
        <div class="head">
            <h1>Поважный Петр Александрович</h1>
            <h3>соискатель на должность программиста</h3>
            <div class="contacts">
                <h4>+7-928-373-16-13</h4>
                <p>e-mail: c592@yandex.ru</p>
                <p>355035, г. Ставрополь</p>
                <p>пр. К. Маркса, 100</p>
            </div>
        </div>
        <div class="about">
            <article>
                <h3>Кратко о себе</h3>
                <p>
                    Мне 32 года (29 августа 1984). Постоянно поживаю в г. Ставрополе. Женат. Ребенок 7 лет.
                </p>
                <p>
                    О себе могу сказать, что я целеустермленный, творческий человек с широким кругом интересов в разных областях.
                    В основном увлекаюсь разработкой ПО для IBM PC, но помимо программирования(о нем чуть позже) увлекаюсь естественными науками, астрономией.
                    Люблю проводить время на свежем воздухе, вдали от городской суеты. Люблю путешествовать, побывал более чем в 10 городах России(от Махачкалы
                    до Пензы). Обладаю широким кругозором, хотя в общении веду себя сдержано.
                </p>
                <p>
                    Разработкой занимаюсь с 2010г. Начиная  с Object Pascal(Delphi 7) в настоящее время работаю в VS15 .Net. Разработка приложений - полный цикл.<br/> Опыт работы с:
                    <ul>
                        <li>MS SQL Server 2010, Firebird;</li>
                        <li>ORM Entity Framework;</li>
                        <li>MVC, MVVM patterns;</li>
                        <li>Frontend HTML CSS;</li>
                        <li>Продвижение Яндекс директ;</li>
                    </ul>
                </p>
            </article>
        </div>
        <div class="education">
            <article>
                <h3>Образование</h3>
                <table class="table table-responsive table-condensed">
                    <thead>
                    <tr>
                        <td>Год <br/>поступления</td>
                        <td>Учебное заведение, специальность</td>
                        <td>Год <br/>окончания</td>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>1992</td>
                        <td>
                            Средняя общеобразовательная школа №1 с углубленным изучением английского языка. Дневная форма обучения.
                        </td>
                        <td>2001</td>
                    </tr>
                    <tr>
                        <td>2001</td>
                        <td>Северо-Кавказский Политехнический Университет. Специальность "Автоматизированные системы обработки и управления (АСОУ)".
                            Обучался на бюджетной основе. Средний бал 4. Синий диплом с отличием.</td>
                        <td>2006</td>
                    </tr>
                    </tbody>
                </table>
            </article>
        </div>
        <div class="army">
            <article>
                <h3>Военная служба</h3>
                <p>Не служил.</p>
            </article>
        </div>
        <div class="work">
            <article>
                <h3>Опыт работы</h3>
                <table class="table table-responsive table-condensed">
                    <thead>
                    <tr>
                        <td>С</td>
                        <td>Место работы</td>
                        <td>Должность</td>
                        <td>По</td>
                        <td>Причина <br/>увольнения</td>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>2003</td>
                        <td>
                            ООО "Принт-Сервис" - торговля компьютерами.
                        </td>
                        <td>Продавец-консультант</td>
                        <td>2005</td>
                        <td>Низкая З/П.</td>
                    </tr>
                    <tr>
                        <td>2005</td>
                        <td>
                            ООО "ПКП "Искра" - торговля компьютерами.
                        </td>
                        <td>Пришел на должность продавца консультанта. На момент увольнения занимал должность Руководителя торговой точки.</td>
                        <td>2007</td>
                        <td>Отсутствие карьерного роста. Предложили более выгодное место работы.</td>
                    </tr>
                    <tr>
                        <td>2007</td>
                        <td>
                            ООО "НПО "Инженерные системы" - системный интегратор.
                        </td>
                        <td>Пришел на должность продавца. Был уволен в должности директора дочерней компании ООО"ТрейдКом"</td>
                        <td>20010</td>
                        <td>Непреодолимые разногласия с руководителем.</td>
                    </tr>
                    <tr>
                        <td>2010</td>
                        <td>
                            Работал агентом, паралельно занимался программированием.
                        </td>
                        <td></td>
                        <td>Настоящее время: Фрилансер</td>
                        <td></td>
                    </tr>
                    </tbody>
                </table>
            </article>
        </div>
        <div class="skils">
            <article>
                <h3>Профессиональные навыки</h3>
                <ul>
                    <li>С#</li>
                    <li>SQL</li>
                    <li>Entity Framework 6 (code first)</li>
                    <li>ASP .Net</li>
                    <li>Web API</li>
                    <li>HTML</li>
                    <li>CSS</li>
                    <li>JS +/-</li>
                    <li>KnockoutJS</li>
                    <li>WPF XAML +/-</li>
                    <li>WCF +/-</li>
                </ul>
            </article>
        </div>
        <div class="develop">
            <article>
                <h3>Опыт в разработке:</h3>
                <p>
                    За период с 2010г. освоил .Net на уровне уверенного пользователя. Оценить свои знания могу на уровне - "Мне говорят, что я крутой программист".
                    В Ставрополе мало вакансий по направлению разработчик .Net, поэтому официального трудоустройства нет, работаю по заказам в частном порядке. 
                    Один из последних проектов www.id-racks.ru. В данном проекте все сделано мной. 
                    Я уравновешенный человек, стрессоустойчив, конструктивно отношусь к критике.
                </p>
                <p>
                    Причины поиска работы - личный рост.
                </p>
            </article>
        </div>
    </div>
</div>

TestApp/Views/Start/PersonsDetails.cshtml
@model IEnumerable<TestApp.Models.Person>
@{
    ViewBag.Title = "PersonsDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section links
{
<link href="~/Content/TestCSS.css" rel="stylesheet" />
}
@section scripts
{
<script src="~/Scripts/jsTest/ajaxProp.js"></script>
<script src="~/Scripts/jsTest/models.js"></script>
<script src="~/Scripts/jsTest/PersonController.js"></script>
}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            @Html.Partial("placeholders/Filters")
        </div>
        <div class="col-md-9">
            <div data-bind="visible:model.currentView()=='list'">
                @Html.Partial("placeholders/listPersons")
            </div>
        </div>
    </div>
</div>

TestApp/Views/Start/Sfj.cshtml
@{
    ViewBag.Title = "Sfj";
    Layout = "~/Views/Shared/_sfj.cshtml";
}

<div class="aboutMe">
    <h3>Добрый день, меня зовут Петр и я ищу работу web-разработчика</h3>
    <div class="imgWrapper">
        <img alt="" src="/Content/img/me.png"/>

    </div>
    <div class="descr">
        <ul>
            <li><i class="fa fa-map-marker fa-2x" aria-hidden="true"></i> проживаю в г. Ставрополь</li>
            <li><i class="fa fa-mobile fa-2x" aria-hidden="true"></i> +7-928-373-16-13</li>
            <li><i class="fa fa-envelope-o fa-2x" aria-hidden="true"> </i><a href="mailto:manfice@yandex.ru"> manfice@yandex.ru</a></li>
            <li><i class="fa fa-skype fa-2x" aria-hidden="true"></i> Skype: manfice</li>
        </ul>
    </div>
</div>
<div class="myProf">
    <h3>Я работаю с</h3>

    <div class="workWith">
        <img alt="" src="/Content/img/net200.png"/>
        <img alt="" src="/Content/img/html200.png"/>
        <img alt="" src="/Content/img/css200.png"/>
        <img alt="" src="/Content/img/js200.png"/>
    </div>
    <h3>среда разработки и инструменты</h3>
    <div class="workWith">
        <img alt="" src="/Content/img/c200.png"/>
        <img alt="" src="/Content/img/vs200.jpg"/>
        <img alt="" src="/Content/img/ef200.jpg"/>
        <img alt="" src="/Content/img/sql200.png"/>
        <img alt="" src="/Content/img/gh200.png"/>
        <img alt="" src="/Content/img/ko200.png"/>

    </div>
</div>
<div class="myPlus">
    <h3>мои преимущества</h3>
    <ul>
        <li>
            <div class="plItem">
                <h4><i class="fa fa-bell-slash-o fa-2x" aria-hidden="true"></i>Стрессоустоичив</h4>
                <p>...</p>
            </div>
        </li>
        <li>
            <div class="plItem">
                <h4><i class="fa fa-graduation-cap fa-2x" aria-hidden="true"></i>Решаю любые задачи</h4>
                <p>...</p>
            </div>
        </li>
        <li>
            <div class="plItem">
                <h4><i class="fa fa-tasks fa-2x" aria-hidden="true"></i>Многозадачный</h4>
                <p>...</p>
            </div>
        </li>
        <li>
            <div class="plItem">
                <h4><i class="fa fa-users fa-2x" aria-hidden="true"></i>Коммуникабельный</h4>
                <p>...</p>
            </div>
        </li>

    </ul>
</div>

TestApp/Views/Start/placeholders/Filters.cshtml
<ul class="menu">
    <li data-bind="click: getPersons()">Все люди</li>
    <li onclick="getGirl(false)">Девушки</li>
    <li onclick="getGirl(true)">Мужчины</li>
    <li>Свободные</li>
    <li>Супруги</li>
</ul>

TestApp/Views/Start/placeholders/listPersons.cshtml
<h2>Список участников:</h2>
<table class="table table-responsive table-striped">
    <thead>
        <tr>
            <td>КОД</td>
            <td>Имя</td>
            <td>Фамилия</td>
            <td>Возраст</td>
        </tr>
    </thead>
    <tbody data-bind="foreach:model.persons()">
        <tr>
            <td data-bind="text: $data.Id"></td>
            <td data-bind="text: $data.FirstName"></td>
            <td data-bind="text: $data.LastName"></td>
            <td data-bind="text: $data.Age"></td>
        </tr>
    </tbody>
</table>